  postgres:
    image: postgres:15-alpine
    container_name: school_mgmt_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_mgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./seed_db/tables.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./seed_db/seed-db.sql:/docker-entrypoint-initdb.d/02-seed-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d school_mgmt"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school_mgmt_backend
    restart: unless-stopped
    ports:
      - "5007:5007"
    environment:
      PORT: 5007
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/school_mgmt
      JWT_ACCESS_TOKEN_SECRET: your_super_secret_access_token_key_here_change_in_production
      JWT_REFRESH_TOKEN_SECRET: your_super_secret_refresh_token_key_here_change_in_production
      JWT_ACCESS_TOKEN_TIME_IN_MS: 900000
      JWT_REFRESH_TOKEN_TIME_IN_MS: 28800000
      CSRF_TOKEN_SECRET: your_csrf_secret_key_here_change_in_production
      CSRF_TOKEN_TIME_IN_MS: 950000
      MAIL_FROM_USER: noreply@yourschool.com
      RESEND_API_KEY: re_dummy_key_for_development_only
      EMAIL_VERIFICATION_TOKEN_SECRET: your_email_verification_secret_here
      EMAIL_VERIFICATION_TOKEN_TIME_IN_MS: 18000000
      PASSWORD_SETUP_TOKEN_SECRET: your_password_setup_secret_here
      PASSWORD_SETUP_TOKEN_TIME_IN_MS: 300000
      UI_URL: http://localhost:5173
      API_URL: http://localhost:5007
      COOKIE_DOMAIN: localhost
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - school_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school_mgmt_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5007/api/v1
    depends_on:
      - backend
    networks:
      - school_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  school_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
